use_frameworks!

target 'FormField_Example' do
  pod 'FormField', :path => '../'

  target 'FormField_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
