use_frameworks!

target 'FormField_Example' do
  pod 'FormField', :path => '../'
end

target 'FormField_Tests' do
    pod 'Quick', '~> 0.9.3'
    pod 'Nimble', '~> 4.1.0'
    pod 'FormField', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end
end
